version: '3'
services:
    angular:
        image: "informaticsmarine/vessel-search"
        ports:
            - "80:80"
        restart: unless-stopped            
    elasticsearch:
        image: "informaticsmarine/allvessels"
        ports:
            - "9200:9200"
        environment:
            - "discovery.type=single-node"
            - "http.cors.enabled=true"
            - "http.cors.allow-origin=*"
        restart: unless-stopped
